import type {Metadata} from "next";

import {Suspense} from "react";
import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "remote-cache-fallback",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      {/* This empty suspense boundary blocks the render until the server is done doing its job */}
      <Suspense>
        <body className="container m-auto grid min-h-screen grid-rows-[auto_1fr_auto] gap-8 px-4 font-sans antialiased">
          <header className="flex items-center justify-between text-xl leading-16 font-bold">
            <Link href="/">remote-cache-fallback</Link>
            <nav>
              <ul className="flex gap-4">
                <li>
                  <Link href="/">Home</Link>
                </li>
                <li>
                  <Link href="/1">1</Link>
                </li>
                <li>
                  <Link href="/2">2</Link>
                </li>
                <li>
                  <Link href="/3">3</Link>
                </li>
              </ul>
            </nav>
          </header>
          {children}
          <footer className="text-center leading-16 opacity-70">remote-cache-fallback</footer>
        </body>
      </Suspense>
    </html>
  );
}
